import { ApiOperation, ApiOkResponse } from '@nestjs/swagger';

import { applyDecorators } from '@nestjs/common';

const ReadAllResponse = {
  description: 'Your all NFTs',
  schema: {
    example: {
      success: true,
      message: 'Your all NFTs',
      result: [
        {
          name: 'MRnft',
          symbol: 'QRNFT',
          royalty: 20,
          image_uri:
            'https://nftstorage.link/ipfs/bafkreiclqyvz2zokfbrdcjv7j43fzcfh2nze4n6nro4n76xobfzy4w4naa',
          cached_image_uri:
            'https://nftstorage.link/ipfs/bafkreiclqyvz2zokfbrdcjv7j43fzcfh2nze4n6nro4n76xobfzy4w4naa',
          metadata_uri:
            'https://nftstorage.link/ipfs/bafkreig3eeamwuupdjnlufa4ld24bh2x2apshvk46xrfooysa5k3ygkdfa',
          description: 'generated by QRaftNFT',
          update_authority: 'BvzKvn6nUUAYtKu2pH3h5SbUkUNcRPQawg4bURBiojJx',
          attributes: {
            speed: 100,
            aggression: 'crazy',
            energy: 'very high',
          },
          attributes_array: [
            {
              trait_type: 'speed',
              value: 100,
            },
            {
              trait_type: 'aggression',
              value: 'crazy',
            },
            {
              trait_type: 'energy',
              value: 'very high',
            },
          ],
          external_url: 'https://shyft.to',
          mint: '2EAMbzr6NKsmzBvoL8cAyndAPPFJgKH8VUrvPdTb9C1J',
          owner: 'BvzKvn6nUUAYtKu2pH3h5SbUkUNcRPQawg4bURBiojJx',
          creators: [
            {
              address: 'J2tQNi4CSusmUs6pvfP26jbXe75DBbTJD8w4pTNyUWMs',
              verified: 1,
              share: 100,
            },
          ],
        },
        {
          name: 'Shyft Founders',
          symbol: 'SF',
          royalty: 5,
          image_uri:
            'https://nftstorage.link/ipfs/bafkreifmnberecudicu36bjwobhh4x57oacmt4z4qq6ulyyb4jwpdmr6de',
          cached_image_uri:
            'https://nftstorage.link/ipfs/bafkreifmnberecudicu36bjwobhh4x57oacmt4z4qq6ulyyb4jwpdmr6de',
          metadata_uri:
            'https://nftstorage.link/ipfs/bafkreiaquw56wi35rggsh3jefna6gnfuuxnwqgp4jilzahbqla2y6ui7la',
          description: 'some description',
          update_authority: 'BvzKvn6nUUAYtKu2pH3h5SbUkUNcRPQawg4bURBiojJx',
          attributes: {
            attack: 200,
            aggression: 'ok',
            energy: 'over 900',
          },
          attributes_array: [
            {
              trait_type: 'attack',
              value: 200,
            },
            {
              trait_type: 'aggression',
              value: 'ok',
            },
            {
              trait_type: 'energy',
              value: 'over 900',
            },
          ],
          external_url: '',
          mint: '5dqRZ7nGBFpU7yc4ZycvfSapzbHwwENxSF967rg5y9b9',
          owner: 'BvzKvn6nUUAYtKu2pH3h5SbUkUNcRPQawg4bURBiojJx',
          creators: [
            {
              address: 'BvzKvn6nUUAYtKu2pH3h5SbUkUNcRPQawg4bURBiojJx',
              verified: 1,
              share: 100,
            },
          ],
        },
      ],
    },
  },
};

export function ReadAllOpenApi() {
  return applyDecorators(
    ApiOperation({ summary: 'Read all NFT from a wallet' }),
    ApiOkResponse(ReadAllResponse),
  );
}

export function ReadAllByCreatorOpenApi() {
  return applyDecorators(
    ApiOperation({ summary: 'Read all NFT from creator address' }),
    ApiOkResponse({
      description: "Creator's all NFTs",
      schema: {
        example: {
          success: true,
          message: "Creator's all NFTs",
          result: {
            nfts: [
              {
                name: 'Cool Monkry',
                symbol: 'CMY',
                royalty: 5,
                image_uri:
                  'https://nftstorage.link/ipfs/bafkreie2ef3z2cixfnxby5zfprv2xa7lydy5biky34v2p2fgsb5b4mcfaa',
                description: 'Shyft makes web3 development so easy.',
                update_authority:
                  'BFefyp7jNF5Xq2A4JDLLFFGpxLq5oPEFKBAQ46KJHW2R',
                attributes: {
                  edification: '100',
                },
                mint: '8bw5T3QxCEU7ZkSH2moydoioefJn8LYoCGUpccjLxkyR',
                owner: 'BFefyp7jNF5Xq2A4JDLLFFGpxLq5oPEFKBAQ46KJHW2R',
              },
            ],
            page: 1,
            size: 2,
            total_data: 9,
            total_page: 5,
          },
        },
      },
    }),
  );
}

export function ReadOpenApi() {
  return applyDecorators(
    ApiOperation({ summary: 'Read NFT  using mint address' }),
    ApiOkResponse({
      description: 'Read NFT using mint address',
      schema: {
        example: {
          success: true,
          message: 'NFT Data',
          result: {
            name: 'Shyft Founders',
            symbol: 'SF',
            royalty: 5,
            image_uri:
              'https://nftstorage.link/ipfs/bafkreifmnberecudicu36bjwobhh4x57oacmt4z4qq6ulyyb4jwpdmr6de',
            cached_image_uri:
              'https://nftstorage.link/ipfs/bafkreifmnberecudicu36bjwobhh4x57oacmt4z4qq6ulyyb4jwpdmr6de',
            metadata_uri:
              'https://nftstorage.link/ipfs/bafkreiaquw56wi35rggsh3jefna6gnfuuxnwqgp4jilzahbqla2y6ui7la',
            description: 'some description',
            update_authority: 'BvzKvn6nUUAYtKu2pH3h5SbUkUNcRPQawg4bURBiojJx',
            attributes: {
              attack: 200,
              aggression: 'ok',
              energy: 'over 900',
            },
            attributes_array: [
              {
                trait_type: 'attack',
                value: 200,
              },
              {
                trait_type: 'aggression',
                value: 'ok',
              },
              {
                trait_type: 'energy',
                value: 'over 900',
              },
            ],
            external_url: 'https://shyft.to',
            mint: '5dqRZ7nGBFpU7yc4ZycvfSapzbHwwENxSF967rg5y9b9',
            owner: 'BvzKvn6nUUAYtKu2pH3h5SbUkUNcRPQawg4bURBiojJx',
            creators: [
              {
                address: 'BvzKvn6nUUAYtKu2pH3h5SbUkUNcRPQawg4bURBiojJx',
                verified: 1,
                share: 100,
              },
            ],
          },
        },
      },
    }),
  );
}
