export const configuration = () => ({
  env: process.env.NODE_ENV,
  awsAccessKeyId: process.env.AWS_ACCESS_KEY_ID,
  awsSecretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
  awsRegion: process.env.AWS_REGION,
  s3Bucket: process.env.S3_BUCKET,
  sesApiVersion: process.env.SES_API_VERSION,
  sesEmailId: process.env.SES_EMAIL_ID,
  mongoURI: process.env.MONGO_URI,
  ipfsGateway: process.env.IPFS_GATEWAY,
  solDevnet: process.env.SOL_DEVNET,
  solMainnetBeta: process.env.SOL_MAINNET_BETA,
  solFallBackMainnet: process.env.SOL_FALLBACK_MAINNET_BETA,
  sentryDSN: process.env.SENTRY_DSN,
  walletSyncTimeInterval: process.env.WALLET_SYNC_TIME_INTERVAL ?? '30',
  nftSyncTimeInterval: process.env.NFT_SYNC_TIME_INTERVAL ?? '120',
  mpTimerInterval: process.env.MP_TIMER_INTERVAL,
  mpTimerExpiration: process.env.MP_TIMER_EXPIRATION,
  minDateOnSearch: '2020-03-16',
});
