# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Solana API CI

on:
  release:
    branches: [ main ]
    action: published

  push:
    branches: [ main ]

jobs:
  test:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts

    - name: Create .env file
      uses: ozaytsev86/create-env-file@v1
      with:
        ENV_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        ENV_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ENV_AWS_REGION: ${{ secrets.AWS_REGION }}
        ENV_SES_API_VERSION: ${{ secrets.SES_API_VERSION }}
        ENV_SES_EMAIL_ID: ${{ secrets.SES_EMAIL_ID }}
        ENV_S3_BUCKET: ${{ secrets.S3_BUCKET }}
        ENV_MONGO_URI: ${{ secrets.MONGO_URI }}
        ENV_IPFS_GATEWAY: ${{ secrets.IPFS_GATEWAY }}
        ENV_SOL_DEVNET: ${{ secrets.SOL_DEVNET }}
        ENV_SOL_MAINNET_BETA: ${{ secrets.SOL_MAINNET_BETA }}
        ENV_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        ENV_SOL_FALLBACK_MAINNET_BETA: ${{ secrets.SOL_FALLBACK_MAINNET_BETA }}

    - name: Build and Test
      run: |
        echo Deployed into this PATH $PWD
        npm run build

  build:
    if: ${{ github.event_name == 'release' }}
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts

    - name: Create .env file
      uses: ozaytsev86/create-env-file@v1
      with:
        ENV_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        ENV_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ENV_AWS_REGION: ${{ secrets.AWS_REGION }}
        ENV_SES_API_VERSION: ${{ secrets.SES_API_VERSION }}
        ENV_SES_EMAIL_ID: ${{ secrets.SES_EMAIL_ID }}
        ENV_S3_BUCKET: ${{ secrets.S3_BUCKET }}
        ENV_MONGO_URI: ${{ secrets.MONGO_URI }}
        ENV_IPFS_GATEWAY: ${{ secrets.IPFS_GATEWAY }}
        ENV_SOL_DEVNET: ${{ secrets.SOL_DEVNET }}
        ENV_SOL_MAINNET_BETA: ${{ secrets.SOL_MAINNET_BETA }}
        ENV_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        ENV_SOL_FALLBACK_MAINNET_BETA: ${{ secrets.SOL_FALLBACK_MAINNET_BETA }}

    - name: Build
      run: |
        echo Deployed into this PATH $PWD
        npm run build
        bash deploy.sh
